### ISSUE TITLE
Signing a fat binary may result in different binary identifier in csreq

### ISSUE THREAD

**Issue by roblabla** [indygreg/apple-platform-rs#12]
Hello,

When I sign an application bundle containing a single fat binary (x86_64 and arm64) with rcodesign, I end up with a fat binary whose slices have different binary identifier in their csreq:

- The x86_64 slice (which comes first) has the correct bundle identifier, derived from the Info.plist
- The aarch64 slice (which comes second) has a weird identifier that looks like `<filename>-<hash>`, which I suspect comes from the ad-hoc signature generated by the linker.

Here's a quick reproducer as a quick-n-dirty bash script:

```bash
echo "int main() { return 0; }" > test.c
clang -target x86_64-apple-darwin test.c -o test-x64
clang -target arm64-apple-darwin test.c -o test-arm64
lipo -create -output test test-x64 test-arm64

mkdir -p Test.app/Contents/MacOS
echo -n 'APPL????' > Test.app/Contents/PkgInfo
cp test Test.app/Contents/MacOS/test

cat > Test.app/Contents/Info.plist  << END
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleExecutable</key>
	<string>test</string>
	<key>CFBundleIdentifier</key>
	<string>quick.test</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>test</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
</dict>
</plist>
END

rcodesign sign Test.app
rcodesign print-signature-info Test.app | grep identifier
```

The final command has this output:

```
          identifier: quick.test
          identifier: test-arm64
```

Whereas I expect the following:

```
          identifier: quick.test
          identifier: quick.test
```

Given that's the identifier specified in the Info.plist.

**Comment by indygreg** [comment]
Thanks for filing this.

The binary identifier logic is a bit convoluted and I'm honestly not sure what the correct logic should be! I feel like someone will have to test what `codesign` does and then emulate that behavior in our code.
