### ISSUE TITLE
pkg signing error

### ISSUE THREAD

**Issue by turalf** [indygreg/apple-platform-rs#140]
While signing a package file I get this error. 
This is the command I use:

> rcodesign sign  --p12-file installer.p12 --p12-password-file ./.certificate-password test.pkg ./test-out.pkg

And I get this error:

> signing test.pkg to ./test-out.pkg
signing XAR pkg installer at test.pkg to ./test-out.pkg.tmp
Error: XAR error: XML error: custom: unknown field `id`, expected one of `name`, `offset`, `size`, `length`, `extracted-checksum`, `archived-checksum`, `encoding`

The command is run on `"Debian GNU/Linux 12 (bookworm)"`

That is how I created the `test.pkg` file on macOS 14.4.1 

> mkdir test-pkg
>  echo "echo test" > test-pkg/echoer
> pkgbuild --identifier test.pkg --root ./test-pkg ./test.pkg

**Comment by indygreg** [comment]
Fixed by #155.
