### ISSUE TITLE
Signing iOS app results in unbound Info.plist

### ISSUE THREAD

**Issue by catshow** [indygreg/apple-platform-rs#43]
Image on left was code signed by macOS codesign.  Right side is from this tool.

<img width="1581" alt="image" src="https://user-images.githubusercontent.com/56951/200143669-7f6b33c6-cd36-49b4-a4a1-c91c139eed5e.png">

Here is a diff of codesign -d -vvvv iOSTestApp.app
```
% diff ~/Desktop/macos.txt ~/Desktop/rust.txt 
< CandidateCDHash sha256=8459bf53a2729671241a130587db4d73ade1060f
> CandidateCDHash sha256=49201689372966eee371d4d03c2f85d58eebf610
< CandidateCDHashFull sha256=8459bf53a2729671241a130587db4d73ade1060fd1133e06793432e8a3025cd6
> CandidateCDHashFull sha256=49201689372966eee371d4d03c2f85d58eebf610008467dead019e2e47f75f46
< CMSDigest=8459bf53a2729671241a130587db4d73ade1060fd1133e06793432e8a3025cd6
> CMSDigest=49201689372966eee371d4d03c2f85d58eebf610008467dead019e2e47f75f46
< CDHash=8459bf53a2729671241a130587db4d73ade1060f
> CDHash=49201689372966eee371d4d03c2f85d58eebf610
< Signature size=4814
> Signature size=4812
< Signed Time=Oct 21, 2022 at 3:10:24 PM
< Info.plist=not bound
> Signed Time=Nov 5, 2022 at 5:32:44 PM
> Info.plist entries=29
```

Note: that Info.plist is not bound on the Mac codesign.  The app is an iOS app if that may cause the difference.

% ls -al iOSTestApp.app/Info.plist 
-rw-r--r--  1 <redacted>  staff  1297 Nov  5 17:32 iOSTestApp.app/Info.plist

**Comment by indygreg** [comment]
The `Info.plist` difference feels like a bug.

Binary size is more nuanced. Somewhere I wrote a long comment about how difficult it is to yield identical binary size as `codesign`. But 11k feels excessive. We should be able to do better.

Can you share more details about the entity that was signed that didn't bind an `Info.plist` with Apple's tooling? What kind of bundle was this? Steps to reproduce?

**Comment by catshow** [comment]
Actually I had the diff wrong, your size was 11k smaller than the macOS signed one.  However, it did pass codesign --verify.

The signed binary was an iOS application bundle that looks like this:

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/56951/200364900-ccb30020-3d7b-425b-ab44-be971d221b2f.png">

Here is most of the Info.plist (there is nothing really special in it).
<img width="912" alt="info-plist" src="https://user-images.githubusercontent.com/56951/200366308-ce9e028f-0357-4fc7-af66-cf47c32d610e.png">

Unfortunately, I am not allowed to make OSS contributions.  Hopefully this helps.

**Comment by indygreg** [comment]
I changed the issue title since I don't believe binary size differences are the main issue here.

**Comment by indygreg** [comment]
I suspect this issue was fixed either in the last release or in the `main` branch as a result of continued work to shore up bundle signing.

Please reopen or file a new issue if the issue remains.
