### ISSUE TITLE
unknown variant `SHA1`, expected one of `none`, `sha1`, `sha256`, `sha512`, `md5`

### ISSUE THREAD

**Issue by astralko** [indygreg/apple-platform-rs#51]
Hello,

I have a pkg that I created using this manual:
http://bomutils.dyndns.org/tutorial.html

it also includes a file that I already signed using rcodesign.

when I try to sign the pkg file, using the same certificate the I used for the other file, I am getting
Error: XAR error: XML error: custom: unknown variant `SHA1`, expected one of `none`, `sha1`, `sha256`, `sha512`, `md5`

is there a workaround or a fix?

thanks!

**Comment by indygreg** [comment]
This looks to be an XML deserialization issue: we're only accepting lowercase digest strings but your file has an uppercase variant. This should be easy to fix.
