### ISSUE TITLE
appstoreconnect: Unauthenticated

### ISSUE THREAD

**Issue by dvc94ch** [indygreg/apple-platform-rs#53]
getting this error, is this a temporary apple server issue? does anyone else have this problem? I can't find anything wrong with the appstoreconnect jwt code.

```
rcodesign notary-submit --api-key-path ~/.apple/notarization.json dioxus-wallet.app
creating Notary API submission for dioxus-wallet.app.zip (sha256: 02f1752798354dad88244220f8361df9571d1c4356ee64dba38994ec88429592)
HTTP error from https://appstoreconnect.apple.com/notary/v2/submissions
Unauthenticated

    Request ID: ICM7THHI5RZTBKUQA3VWJCUECA.0.0

Error: error interacting with Notary API
```

**Comment by dvc94ch** [comment]
for some reason ntp wasn't enabled so there was a slight clock skew I didn't notice :man_facepalming:

**Comment by rjzak** [comment]
I'm getting this error and NTP synchronization is enabled (and run explicitly with `sudo sntp -sS time.apple.com`).
