### ISSUE TITLE
The executable could not be re-signed for submission to the App Store

### ISSUE THREAD

**Issue by dvc94ch** [indygreg/apple-platform-rs#56]
Built my app with `xbuild` which uses `apple-codesign` internally. Validated/uploaded the app with `altool` which completed successfully. Shortly after that I received an email from apple with the following contents:

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "***" 0.1.0 (0.1.0). Please
correct the following issues, then upload again.

ITMS-90135: The executable could not be re-signed for submission to the App Store. The app may
have been built or signed with non-compliant or pre-release tools.

Best regards,

The App Store Team
```

**Comment by dvc94ch** [comment]
this very unhelpful error message comes from using a timestamp server with a distribution provisioning profile.

**Comment by roblabla** [comment]
Could we perhaps detect this case and provide a helpful warning in rcodesign?

**Comment by dvc94ch** [comment]
Not sure how to reliably detect what kind of profile it is. In xbuild I check if devices are configured, I assume it's a development profile. But I think adhoc profiles also list devices.
