### ISSUE TITLE
Testflight support

### ISSUE THREAD

**Issue by russelltg** [indygreg/apple-platform-rs#59]
Is there any potential for support for uploading to TestFlight?

It is unfortunately not a part of the AppStore connect API as far as I can tell, so the API may have to be reverse engineered....

**Comment by russelltg** [comment]
I think this may be a duplicate or related to #55 ?

**Comment by dvc94ch** [comment]
yes, this is indeed a duplicate. for now the simplest way is using `altool` in a macos github runner.
