### ISSUE TITLE
rcodesign verify doesn't like executables it has just signed

### ISSUE THREAD

**Issue by kornelski** [indygreg/apple-platform-rs#65]
I'd expect that if I run `rcodesign sign exe` followed by `rcodesign verify exe`, then the verification will succeed. However, the tool reports conflicting information — signing seems to succeed, but its verification fails.

To reproduce: (tested on macOS Ventura 13.2)

```bash
cargo new --bin hello
cd hello
cargo build --release
rcodesign sign target/release/hello
rcodesign verify target/release/hello
```

```text
$ rcodesign sign target/release/hello
signing target/release/hello in place
signing target/release/hello as a Mach-O binary
inferring default signing settings from Mach-O binary
preserving existing binary identifier in Mach-O
preserving code signature flags in existing Mach-O signature
setting binary identifier to hello
parsing Mach-O
signing Mach-O binary at index 0
binary targets macOS >= 11.0.0 with SDK 13.1.0
adding code signature flags from signing settings: ADHOC | LINKER_SIGNED
creating ad-hoc signature
removing linker signed flag from code signature (we're not a linker)
code directory version: 132096
total signature size: 3927 bytes
writing Mach-O to target/release/hello
$ rcodesign verify target/release/hello
no cryptographic signature present
Error: problems reported during verification
```

Even weirder that Apple's codesign does validate it okay:

```text
$ codesign -vv target/release/hello
target/release/hello: valid on disk
target/release/hello: satisfies its Designated Requirement
```

**Comment by indygreg** [comment]
As I just wrote in #67, our verification code isn't great. I've thought about deleting most of it because it is a big pile of complexity to maintain. The main reason I'd like to keep it is that it can serve as a check that our signing code works as expected. But at the end of the day Apple's verification code is the only code that matters. I strongly encourage use of Apple's `codesign` to verify signing performed by `rcodesign`. Note that you get this verification implicitly during notarization.

**Comment by kornelski** [comment]
Too bad the verification code isn't in a good shape. I'm trying to figure out why Apple is refusing to notarize my application, but Apple doesn't have tools for debugging code signing issues. I've reported to them that`codesign` and `spctl` don't sufficiently explain why verification failed, and Apple responded that these tools are not supposed be used for debugging, and it's intentional that they do not give any details!
