### ISSUE TITLE
More minimal codesigning

### ISSUE THREAD

**Issue by wolfv** [indygreg/apple-platform-rs#70]
Hi, thanks for the awesome project. We've started to use it in the [`rattler`](https://github.com/mamba-org/rattler) package manager where we only need self-signing.

Unfortunately, this crate has quite a lot of bells and whistles that we don't really need for just self-signing and I was wondering if it's possible to add a `minimal` feature  that removes the dependency on AWS crates and similar.

**Comment by indygreg** [comment]
I agree the dependency tree is quite... large.

I am supportive of adding crate features to trim fat to support narrower use cases.

I'm not sure if/when I'll have time to work on this. But I would accept PRs!

Is this something you'd be interested in contributing?

**Comment by naturecodevoid** [comment]
I am interested in contributing this; I'm planning to put `aws-config`, `aws-sdk-s3`, and `aws-smithy-http` in a `aws-notarization-upload` feature, but most of the other dependencies seem essential so I'm not really sure what else to put in a feature.

**Comment by baszalmstra** [comment]
With #78 merged, would it be possible to create a new release so that we can shed some dependencies? :) @indygreg

**Comment by wolfv** [comment]
Unfortunately our builds also started to break because of an old version of `rasn` that is pulled in as a dependency of apple-codesign. A release would be greatly appreciated! :)
