### ISSUE TITLE
What is the LICENSE ?

### ISSUE THREAD

**Issue by pamidur** [indygreg/apple-platform-rs#80]
Hi!

I was wondering what is the license for this software? Can I distribute "rcodesign" executable with my own opensource software?

Thank you!

**Comment by roblabla** [comment]
rcodesign is licensed with MPL 2.0. According to that license, you may distribute it freely, so long as you make available any changes done to the source code of rcodesign, and inform your users of where they can acquire its source.

**Comment by pamidur** [comment]
Thank you!
