### ISSUE TITLE
[Linux] Binary setted as CFBundleExecutable in Info.plist file does not signed.

### ISSUE THREAD

**Issue by warlockosx** [indygreg/apple-platform-rs#81]
While trying to sign app bundle on Linux - binary SomeApp.app/Contents/MacOS/SomeApp which is CFBundleExecutable in Info.plist - not signing. If sign it manually - got an error while trying to notirize - "Invalid binary signature".
If make copy of SomeApp to SomeApp.copy and set SomeApp.copy to CFBundleExecutable, then SomeApp will be signed and SomeApp.copy - No. Is there some workaround to fix this?

**Comment by indygreg** [comment]
How are you invoking signing? Would you be able to paste output to help debugging?

When signing a bundle, `<bundle>/Contents/MacOS/<CFBundleExecutable>` should be recognized as the main executable and signed appropriately. So I'm not sure what's going on here without more info to help debugging.

**Comment by indygreg** [comment]
Without steps to reproduce, I'm going to assume this was fixed in the recent set of improvements to bundle signing. Please reopen with steps to reproduce if not.
