### ISSUE TITLE
rcodesign verify file.sh fails with Invalid magic number: 0x23212f62

### ISSUE THREAD

**Issue by dsehrawa** [indygreg/apple-platform-rs#86]
rcodesign verify file.sh

fails with on MacOS:-

Mach-O parse failure: binary parsing error: Invalid magic number: 0x23212f62
Error: problems reported during verification

The apple 
**codesign -dvvv file.sh** shows the certificate correctly

**Comment by indygreg** [comment]
The `verify` command currently assumes the path is a Mach-O binary. The verification code hasn't been touched since we added support for bundles and other signable entity types.

**Comment by indygreg** [comment]
I believe this was _fixed_ in 187aedd9798351fca3d4926998167a902fcc64e0. If there's a missing feature you are requesting, please file a new issue.
