### ISSUE TITLE
Error: YAML serialization error: serializing nested enums in YAML is not supported yet

### ISSUE THREAD

**Issue by markshep-wbg** [indygreg/apple-platform-rs#92]
I'm trying to debug an issue with a macOS app generated by [Unity](https://unity.com/) but can't run `rcodesign print-signature-info` on the app as it exits with this error:

```
Error: YAML serialization error: serializing nested enums in YAML is not supported yet
```

I've made a trivial test app to demonstrate the problem which I can upload if it would help?  It's 34MB compressed.

**Comment by indygreg** [comment]
This should be fixed by commit 33fad6ad36f1ae98d0b7183825ed5ee8c3bf4a8b.
